filebeat.inputs:
  - type: filestream
    id: microservice
    fields_under_root: true
    encoding: utf-8
    fields:
      event.dataset: microservice
    paths:
      - /var/log/microservice/*.log

setup.kibana:
  host: "kibana:5601"
output.logstash:
  hosts: 'logstash:5001'